# Generated by Django 3.2.7 on 2021-12-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='newbook',
            name='synopsis',
            field=models.CharField(default=None, max_length=700),
        ),
    ]
