# Generated by Django 3.2.7 on 2021-12-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_newbook_synopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newbook',
            name='synopsis',
            field=models.CharField(max_length=700),
        ),
    ]
