# Generated by Django 3.2.7 on 2021-12-24 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_newbook_synopsis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newbook',
            name='synopsis',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.URLField(max_length=400)),
                ('book', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='books.newbook')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
