# Generated by Django 3.2.7 on 2021-12-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20211223_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
