# Generated by Django 3.2.7 on 2021-12-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='newbook',
            name='synopsis',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
