# Generated by Django 3.2.7 on 2021-12-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20211223_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='newbook',
            name='synopsis',
            field=models.CharField(default=None, max_length=400),
        ),
    ]
